name: Copilot Setup Steps
true:
  workflow_dispatch: null
  pull_request:
    paths:
    - .github/workflows/copilot-setup-steps.yml
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: dotnet/modernize-dotnet-actions@main
      with:
        dotnet-version: 10.0.x
